# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd3f80ffa16f0be09fba676b2258d0eb2296ee82e1595cb2925bf8b3fed98275dee46178543fd9c0a75ca28a50b502c02d5c9965bb751435dcfd655770f256d

test:
  secret_key_base: 49efbd57b0e9797b548c05458d35b938e13859f792dcb674cfdd590b6145602c72527aa8210ae21b93f8e7a6a4a25f51918af23806c1f7a0b2b4885c8566773a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
